site_name: RiseML Documentation
header_name: Documentation
site_url: https://riseml.com
site_author: RiseML
repo_url: https://github.com/riseml/riseml
edit_uri: blob/master/docs
repo_name: riseml/riseml
docs_dir: docs
site_description: 'Documentation for RiseML'
theme:
  name: material
  favicon: images/favicon.ico
  logo: 'images/riseml@2x.png'
  custom_dir: 'docs/theme'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  language: en
  font:
    text: ProximaNovaRegular
    code: Inconsolata
  feature:
    tabs: true

extra_css:
    - css/style.css

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Customization
extra:
  social:
    - type: globe
      link: http://riseml.com
    - type: github-alt
      link: https://github.com/riseml
    - type: twitter
      link: https://twitter.com/riseml


pages:
  - Overview:
    - About RiseML: index.md
    - Quick Start: quick_start.md
    - Understanding RiseML: understanding.md
  - Installation &amp; Setup:
    - Overview: install/index.md
    - Quick Setup: install/quicksetup.md
    - Check Requirements: install/requirements.md
    - Configure Kubernetes: install/kubernetes.md
    - Configure RiseML: install/configuration.md
    - Install RiseML: install/riseml.md
    - Install CLI: install/cli.md
    - Check and Register: install/register.md
    - Troubleshooting: install/troubleshooting.md
  - Usage:
    - Overview: guide/index.md
    - Preparation: guide/preparation.md
    - Starting Experiments: guide/starting.md
    - Monitoring Experiments: guide/monitoring.md
    - Writing Output: guide/output.md
    - Starting Experiments on GPU: guide/gpus.md
    - TensorBoard: guide/tensorboard.md
    - Advanced Usage:
      - Hyperparameter Optimization: guide/advanced/hyper.md
      - Distributed TensorFlow: guide/advanced/distributed_tensorflow.md
      - Horovod: guide/advanced/horovod.md
      - Customizing Images: guide/advanced/custom_images.md
  - Managing RiseML:
    - User Management: managing/user_management.md
    - Upgrade &amp; Uninstall: managing/upgrade_uninstall.md
  - Reference:
    - Experiment:
      - Configuration: reference/experiments/config.md
      - States: reference/experiments/states.md
      - Identifiers: reference/experiments/canonical_ids.md
    - Runtime Environment: reference/environment.md
    - Command-Line Interface: reference/cli.md
    - Client Library: reference/client/README.md